#!/usr/bin/env bash

# arbitrarily get the most recent four BOSS files in /data/spectro
# and show them in ds9

trap "/bin/rm -f ds9boss4last$$" ERR EXIT

echo Sending to ds9: > /dev/stderr
ls -1t /data/spectro/`sjd.py`/*.fit.gz \
 | head -4 \
 | sort \
 | tee /dev/stderr \
 | tr \\n ' ' \
 | sed 's/^/ds9 -tile -histequ -zoom to fit /' \
 > ds9boss4last$$
 . ds9boss4last$$
