#!/usr/bin/env bash

# arbitrarily get the most recent four guider files in /data/gcam
# and show them in ds9

echo guider observation numbers being sent to ds9: > /dev/stderr
ls -1rt /data/gcam/`sjd.py`/*.fits.gz \
  | tail -4 \
  | tee /dev/stderr \
  | tr \\n \  \
  | sed 's/^.*$/ds9 -tile -histequ -zoom to fit &/' \
  | bash
