#!/usr/bin/env bash

echo unsubscribe bernie@apo.nmsu.edu ucvizauw | mail -s 'unsubscribe bernie@apo.nmsu.edu' apodaylog-request@sdss.org
echo unsubscribe bernie@apo.nmsu.edu itepixah | mail -s 'unsubscribe bernie@apo.nmsu.edu' apogee2-chile-hw-request@sdss.org
echo unsubscribe bernie@apo.nmsu.edu ytinummoc | mail -s 'unsubscribe bernie@apo.nmsu.edu' community-request@xmail.apo.nmsu.edu
echo unsubscribe bernie@apo.nmsu.edu strela-lacitirc | mail -s 'unsubscribe bernie@apo.nmsu.edu' critical-alerts-request@xmail.apo.nmsu.edu
echo unsubscribe bernie@apo.nmsu.edu feuzdumo | mail -s 'unsubscribe bernie@apo.nmsu.edu' eboss-request@sdss.org
echo unsubscribe bernie@apo.nmsu.edu erutcurtsarfni | mail -s 'unsubscribe bernie@apo.nmsu.edu' infrastructure-request@sdss.org
echo unsubscribe bernie@apo.nmsu.edu ophutugi | mail -s 'unsubscribe bernie@apo.nmsu.edu' obs-request@sdss.org
echo unsubscribe bernie@apo.nmsu.edu rowuozuh | mail -s 'unsubscribe bernie@apo.nmsu.edu' plug-request@sdss.org
echo unsubscribe bernie@apo.nmsu.edu ummoadog | mail -s 'unsubscribe bernie@apo.nmsu.edu' sdss4-general-request@sdss.org
echo unsubscribe bernie@apo.nmsu.edu umhewefe | mail -s 'unsubscribe bernie@apo.nmsu.edu' sdss5-general-request@sdss.org
echo unsubscribe bernie@apo.nmsu.edu egenuten | mail -s 'unsubscribe bernie@apo.nmsu.edu' sdss5-operations-request@sdss.org
echo unsubscribe bernie@apo.nmsu.edu obhubafo | mail -s 'unsubscribe bernie@apo.nmsu.edu' sloan-25mlog-request@sdss.org
