#!/usr/bin/env python3
#
# Calculate the piston move from the full HArtmann results
#
# ask dmbiz

import sys

scale = -340.  # -- steps per degree

if len(sys.argv) != 3 and len(sys.argv) != 5:
    print("Specify Blue Ring and Red Piston position!")
    print("Syntax:  hart4 blue red")
    print("         OR")
    print("         hart4 blue(sp1) red(sp1) blue(sp2) red(sp2)")
    print("=======================\r")
else:

    if len(sys.argv) == 3:
        bb = sys.argv[1]
        rr = sys.argv[2]
        md = 0.5 * (float(rr) + float(bb) * scale)
        sd = 0.5 * abs(float(rr) - float(bb) * scale)
        # -sd = abs(md - float(rr))
        sg = sd / abs(scale)
        mds = str(int(md))

        print('You entered: b = %s r = %s ' % (bb, rr))
        print()
        print('Predicted piston move : %s, difference %s (%4.1f deg)' % (
        md, sd, sg))
        print()
        print('SELECT CORRECT SPECTROGRAPH below !')
        print('boss moveColl spec=sp1 a=%s b=%s c=%s' % (mds, mds, mds))
        print('boss moveColl spec=sp2 a=%s b=%s c=%s' % (mds, mds, mds))

    if len(sys.argv) == 5:
        bb1 = sys.argv[1]
        rr1 = sys.argv[2]
        bb2 = sys.argv[3]
        rr2 = sys.argv[4]

        md1 = 0.5 * (float(rr1) + float(bb1) * scale)
        sd1 = abs(md1 - float(rr1))
        sg1 = sd1 / abs(scale)
        mds1 = str(int(md1))
        md2 = 0.5 * (float(rr2) + float(bb2) * scale)
        sd2 = abs(md2 - float(rr2))
        sg2 = sd2 / abs(scale)
        mds2 = str(int(md2))

        print('You entered: b1 = %s r1 = %s b2 = %s r2 = %s' % (
        bb1, rr1, bb2, rr2))
        print()
        print('Predicted piston move SP1: %s, difference %s (%4.1f deg)' % (
        md1, sd1, sg1))
        print('Predicted piston move SP2: %s, difference %s (%4.1f deg)' % (
        md2, sd2, sg2))
        print()
        print('boss moveColl spec=sp1 a=%s b=%s c=%s' % (mds1, mds1, mds1))
        print('boss moveColl spec=sp2 a=%s b=%s c=%s' % (mds2, mds2, mds2))
