#!/bin/bash

#  ls -la the directory of /data/mcptpm/{mjd}
#  if no parameters, it used current mjd.
#     mcptpm

# for old mjd, call with  mjd as parameter. 
#    mcptpm 56345

# we use it for afternoon prep to check if mcptpm log is loading. 
# EM: 02/22/2013 


if [[ $# == 0 ]]
then
  dd=$(sjd.py)
else
  dd=$1
fi                

pt=/data/mcptpm/${dd}
echo ${pt}

ls -la ${pt}
