#!/usr/bin/env bash

# filters output of elena's "list_all" and prints lines if they represent
# collimator actuator moves
#
# a hack that can be used to verify actuator moves.

# bernie & elena Fri. 12 Oct. '18

[[ $# -gt 0 ]] && { echo Script \"`basename $0`\" takes no command-line arguments. > /dev/stderr ; echo It is used to note collimator actuator moves recorded in FITS headers. > /dev/stderr ; exit 1 ; }


echo 'CURRENT SJD '`sjd.py`' COLLIMATOR PISTON MOVES RECORDED IN FITS                                 MOTION RECORDED'
echo '                                                                                      -----------------------'
echo '    time  filename   cart plt flav hrt     exp  colA   colB   colC   Motion?             colA    colB    colC Hrt'
echo '    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ======= ======= ======= ----'
( for camera in b1 b2 r1 r2
  do
    echo ""
	list_all 2>/dev/null \
	  | grep -v 'Reading FITS from /data/spectro/' \
	  | sed 's/^\(.*\)[	 ]*\(HART.*\)$/HART\1/' \
	  | grep $camera \
	  | awk 'BEGIN { a=0 ; b=0 ; c=0 } \
		{ d=$(NF-2) ; e=$(NF-1) ; f=$NF ; printf("%s\tMotion recorded:%8d%8d%8d\n", $0, d-a, e-b, f-c) ; a=d ; b=e ; c=f }' \
	  | grep -v '[ 	][ 	]*0[ 	][ 	]*0[ 	][ 	]*0[ 	]*$' \
	  | sed '1s/\([	 ][ 	]*\)Motion recorded:[^H]*/\1                                      /'
  done ) \
| sed -e 's/[	 ]*\(Motion recorded:\)/  \1/' -e 's/^\(HART\)\(.*\)/\2 \1/' \
| sed 's/^[ 0-9][ 0-9][ 0-9][ 0-9]/    /'
