#!/usr/bin/env python3 

"""spVersion - get versions of idlmapper and idlspec2d for night log"""

import os
 
if __name__ =="__main__":
    #sos="source /home/sdss3/products/eups/bin/setups.sh; setup idlspec2d; idlspec2d_version"
    sos="setup idlspec2d; idlspec2d_version"
    sosVer=os.popen(sos).read() 

    map='setup idlmapper; echo "print,idlmapper_version()" | idl 2> /dev/null &' 
    mapVer=os.popen(map).read() 

    print('-- Other versions ----')
    print("idlspec2d         :", str(sosVer).rstrip())
    print("plate-mapper3     :", str(mapVer).rstrip())

    petuniaCmd='readlink /home/sdss4/products/Linux64/petunia/current'
    petuniaVersion=os.popen(petuniaCmd).read() 
    print("petunia           :", str(petuniaVersion).rstrip())

    autoschedulerCmd='readlink /home/sdss4/products/Linux64/autoscheduler/current'
    autoschedulerVersion=os.popen(autoschedulerCmd).read() 
    print("autoscheduler     :", str(autoschedulerVersion).rstrip())
    
    sdss_python_modCmd="readlink /home/sdss4/products/Linux64/sdss_python_module/current"
    sdss_python_modVersion=os.popen(sdss_python_modCmd).read() 
    print("sdss_python_module:", str(sdss_python_modVersion).rstrip())

    mangadrp_Cmd="/home/manga/products/Linux64/mangadrp/trunk/bin/mangadrp_version"
    mangadrp_Version=os.popen(mangadrp_Cmd).read() 
    print("mangadrp          :", str(mangadrp_Version).rstrip())
    
    print("")



