from(bucket: "actors")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "jaeger")
  |> filter(fn: (r) => r["_field"] == "configuration_loaded_1")
  |> filter(fn: (r) => r["cerebro"] == "cerebro")
  |> filter(fn: (r) => r["cerebro_host"] == "sdss5-hub.apo.nmsu.edu")
  |> filter(fn: (r) => r["observatory"] == "APO")
  |> filter(fn: (r) => r["source"] == "tron")
  |> yield()
